CREATE OR REPLACE PROCEDURE MODIFY_HEADER (
    IN_FILE_PATH VARCHAR(1024),
    IN_DB_FILE_NAME VARCHAR(1024)
)
LANGUAGE SQL
SPECIFIC MODIFY_HEADER
MODIFIES SQL DATA
BEGIN

    DECLARE CURSOR_FILE CURSOR FOR
    SELECT VALUE FROM LIBRARY.FILELIST
    WHERE KEY IN (
        SELECT SUBSTR(HEADER, INSTR(HEADER, '/') + 1) FROM (
            SELECT SUBSTR(LINE, INSTR(LINE, '"') + 1) AS HEADER
            FROM TABLE(SYSTEM.QSYS2.OBJECT_STATISTICS('/QSYS.LIB/' CONCAT IN_FILE_PATH CONCAT '.FILE/*' CONCAT ')')
            WHERE FILE_TYPE IN ('STMF', 'MBR')
        ) AS T1
        WHERE RIGHT(HEADER, 2) IN ('.C', '.c', '.H', '.h', '.A')
    );

    DECLARE V_FILE_PATH VARCHAR(1024);
    DECLARE V_HEADER_PATH VARCHAR(1024);
    DECLARE V_HEADER_NAME VARCHAR(1024);

    DECLARE EXIT HANDLER FOR NOT FOUND
    BEGIN
        -- Do nothing
    END;

    OPEN CURSOR_FILE;

    FETCH CURSOR_FILE INTO V_HEADER_PATH;
    WHILE (SQLSTATE = '00000') DO
        SET V_FILE_PATH = SUBSTR(V_HEADER_PATH, 1, LENGTH(V_HEADER_PATH) - LENGTH(SUBSTR(V_HEADER_PATH, INSTR(REVERSE(V_HEADER_PATH), '/') - 1)));

        SELECT VALUE INTO V_HEADER_NAME FROM LIBRARY.FILELIST
        WHERE KEY = SUBSTR(V_HEADER_PATH, INSTR(V_HEADER_PATH, '/') + 1);

        IF (V_HEADER_NAME IS NULL) THEN
            SIGNAL SQLSTATE '70001' SET MESSAGE_TEXT = 'Header file not found in database: ' CONCAT V_HEADER_PATH;
        END IF;

        UPDATE TABLE(SYSTEM.QSYS2.OBJECT_STATISTICS('/QSYS.LIB/' CONCAT IN_FILE_PATH CONCAT '.FILE/*' CONCAT ')')
        SET TEXT = REPLACE(TEXT, '#include "' CONCAT V_HEADER_NAME CONCAT '"', '#include "' CONCAT V_HEADER_PATH CONCAT '"')
        WHERE FILE_TYPE IN ('STMF', 'MBR')
        AND TEXT LIKE '%#include "' CONCAT V_HEADER_NAME CONCAT '"%';

        FETCH CURSOR_FILE INTO V_HEADER_PATH;
    END WHILE;

    CLOSE CURSOR_FILE;

END
